# Generated by Django 5.0.3 on 2024-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_phone_appointment_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
