# Generated by Django 5.0.3 on 2024-03-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_appointment_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/%Y/%m/%d'),
        ),
    ]
